/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    designs: Design;
    products: Product;
    'product-variants': ProductVariant;
    showrooms: Showroom;
    articles: Article;
    authors: Author;
    'journal-categories': JournalCategory;
    categories: Category;
    rooms: Room;
    tags: Tag;
    materials: Material;
    collections: Collection;
    media: Media;
    inquiries: Inquiry;
    subscribers: Subscriber;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    designs: DesignsSelect<false> | DesignsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'product-variants': ProductVariantsSelect<false> | ProductVariantsSelect<true>;
    showrooms: ShowroomsSelect<false> | ShowroomsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    'journal-categories': JournalCategoriesSelect<false> | JournalCategoriesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    rooms: RoomsSelect<false> | RoomsSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    materials: MaterialsSelect<false> | MaterialsSelect<true>;
    collections: CollectionsSelect<false> | CollectionsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    home: Home;
    about: About;
    atelier: Atelier;
    contact: Contact;
    faq: Faq;
    care: Care;
    events: Event;
    privacy: Privacy;
    returns: Return;
    shipping: Shipping;
    'site-config': SiteConfig;
    terms: Term;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    atelier: AtelierSelect<false> | AtelierSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    care: CareSelect<false> | CareSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    privacy: PrivacySelect<false> | PrivacySelect<true>;
    returns: ReturnsSelect<false> | ReturnsSelect<true>;
    shipping: ShippingSelect<false> | ShippingSelect<true>;
    'site-config': SiteConfigSelect<false> | SiteConfigSelect<true>;
    terms: TermsSelect<false> | TermsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * نقش تعیین می‌کند کاربر به کدام بخش‌ها دسترسی دارد.
   */
  role: 'admin' | 'editor' | 'marketing' | 'viewer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "designs".
 */
export interface Design {
  id: number;
  name: string;
  /**
   * Auto-generated from name if left empty
   */
  slug?: string | null;
  /**
   * Exact age group names pending brand decision (OD-3)
   */
  age_group?: ('infant' | 'child' | 'teen' | 'adult') | null;
  /**
   * این طرح در کدام صفحات هاب «سرویس خواب /bedroom-set/{slug}» نمایش داده شود؟ انتخاب چند گزینه ممکن است. خالی یعنی هیچ هاب آرایش‌نشده‌ای نمایش نمی‌دهد.
   */
  occupancies?: ('baby' | 'teen' | 'double' | 'bunk')[] | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * یک جمله‌ی کوتاه و گویا که زیر نام طرح در صفحه‌ی اختصاصی نمایش داده می‌شود.
   */
  tagline?: string | null;
  /**
   * تصویر ابتدای صفحه‌ی طرح (متفاوت از گالری). در صورت خالی بودن، اولین تصویر گالری استفاده می‌شود.
   */
  heroMedia?: (number | null) | Media;
  /**
   * مدیای کارت این طرح در اسلایدر صفحه‌ی /designs (ترجیحاً GIF یا ویدیوی کوتاه که کل ست را نشان می‌دهد). اگر خالی باشد، از heroMedia یا گالری استفاده می‌شود.
   */
  sliderMedia?: (number | null) | Media;
  /**
   * متن بلند با امکان درج تصویر، ویدیو/گیف، نقل قول و ارجاع به متریال.
   */
  storyBlocks?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  gallery?: (number | Media)[] | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Required for accessibility unless decorative
   */
  alt?: string | null;
  caption?: string | null;
  /**
   * When true, alt text is not required
   */
  decorative?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  /**
   * Auto-generated from name if left empty
   */
  slug?: string | null;
  /**
   * یک جمله کوتاه که حس محصول را می‌رساند
   */
  tagline?: string | null;
  /**
   * حداکثر ۲۰۰ کاراکتر — برای کارت‌ها و متاتگ
   */
  shortDescription?: string | null;
  longDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  design: number | Design;
  piece_type?:
    | (
        | 'bed'
        | 'nightstand'
        | 'closet'
        | 'dresser'
        | 'mirror'
        | 'desk'
        | 'bookcase'
        | 'display_cabinet'
        | 'vanity'
        | 'chair'
        | 'console'
        | 'changing_table'
        | 'bracket'
        | 'sofa'
      )
    | null;
  /**
   * این قطعه به کدام گروه‌(های) سنی ست تعلق دارد؟ انتخاب چند گزینه ممکن است. در PDP طرح با ?age=… فیلتر می‌شود. خالی یعنی فیلتر سنی روی این قطعه اثری ندارد.
   */
  occupancies?: ('baby' | 'teen' | 'double' | 'bunk')[] | null;
  categoryIds?: (number | Category)[] | null;
  tagIds?: (number | Tag)[] | null;
  materialIds?: (number | Material)[] | null;
  /**
   * شناسه‌ی یکتای محصول (می‌تواند الگوی AAA-NNN یا عددی باشد).
   */
  sku: string;
  /**
   * قیمت به ریال، عدد صحیح. نمایش تومان توسط رابط کاربری انجام می‌شود.
   */
  basePriceRials: number;
  /**
   * اختیاری — جایگزین قیمت پایه. نمایش در پکیج ۲ فعال می‌شود.
   */
  salePriceRials?: number | null;
  availability: 'in_stock' | 'made_to_order' | 'backorder' | 'discontinued';
  leadTimeDays: number;
  /**
   * سال‌های گارانتی ساختار. نمایش در سایدبار PDP.
   */
  warrantyYears?: number | null;
  /**
   * سال‌های خدمات پس از فروش. نمایش در سایدبار PDP.
   */
  afterSalesYears?: number | null;
  dimensions?: {
    width?: number | null;
    height?: number | null;
    depth?: number | null;
  };
  gallery?: (number | Media)[] | null;
  specs?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * برای ردیف «محصولات مرتبط» در صفحه‌ی محصول
   */
  relatedProductIds?: (number | Product)[] | null;
  /**
   * برای ردیف «در کنار آن خوب است» در صفحه‌ی محصول
   */
  pairsWithProductIds?: (number | Product)[] | null;
  inquiry_enabled?: boolean | null;
  featured?: boolean | null;
  /**
   * هرچه کمتر، بالاتر
   */
  featuredOrder?: number | null;
  /**
   * محصولات «پیش‌نویس» روی سایت نمایش داده نمی‌شوند. فقط ویراستار یا مدیر می‌تواند منتشر کند.
   */
  status: 'draft' | 'published';
  publishedAt?: string | null;
  /**
   * این فیلدها برای بهینه‌سازی موتورهای جستجو هستند. اگر خالی بگذارید، از عنوان و توضیح اصلی صفحه استفاده می‌شود.
   */
  seo?: {
    /**
     * عنوانی که در نتایج گوگل نشان داده می‌شود. بین ۵۰ تا ۶۰ کاراکتر توصیه می‌شود. اگر خالی باشد، عنوان اصلی صفحه استفاده می‌شود.
     */
    metaTitle?: string | null;
    /**
     * توضیح یک یا دو جمله‌ای زیر عنوان در نتایج گوگل. ۱۵۰ تا ۱۶۰ کاراکتر ایده‌آل است.
     */
    metaDescription?: string | null;
    /**
     * تصویری که در شبکه‌های اجتماعی و اپ‌های پیام‌رسان هنگام اشتراک‌گذاری لینک نمایش داده می‌شود. ابعاد پیشنهادی: ۱۲۰۰×۶۳۰. اگر خالی باشد، تصویر کاور خودکار ساخته می‌شود.
     */
    ogImage?: (number | null) | Media;
    /**
     * اگر این محتوا در جای دیگری نسخه اصلی دارد (مثلاً یک مجله‌ی دیگر) اینجا را پر کنید. معمولاً خالی بگذارید.
     */
    canonicalUrl?: string | null;
    /**
     * اگر روشن باشد، این صفحه در نتایج گوگل نمایش داده نمی‌شود. برای صفحات تست یا در حال ساخت مفید است.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Auto-generated from name if left empty
   */
  slug?: string | null;
  /**
   * یک خط برای متاتگ / SEO. متن طولانی hub در فیلد «مقدمه» می‌رود.
   */
  description?: string | null;
  /**
   * یک جمله کوتاه که زیر نام دسته‌بندی در hero نمایش داده می‌شود.
   */
  tagline?: string | null;
  /**
   * تصویر تمام‌عرض بالای صفحه. برای parent‌ها الزامی؛ برای leaf‌ها اختیاری — در صورت خالی بودن، اولین تصویر اولین محصول این دسته استفاده می‌شود.
   */
  cover?: (number | null) | Media;
  /**
   * ۲ تا ۳ پاراگراف کوتاه پس از hero. متن اصلی SEO صفحه. حدود ۱۰۰ کلمه.
   */
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * از xlsx برای leaf‌ها: size, footboard, doors, drawers, glass, width, pieces. برای parent‌ها خالی می‌ماند.
   */
  allowed_axes?: string[] | null;
  /**
   * از xlsx: یادداشت داخلی. روی صفحه‌ی عمومی نمایش داده نمی‌شود.
   */
  rule?: string | null;
  /**
   * فقط برای صفحات SEO-promoted facet (مثل /storage/wardrobe/double-door). شکل: { "axis": "doors", "value": "2" }. صفحه به‌طور خودکار محصولات را با این محور فیلتر می‌کند. برای parent و leaf معمولی خالی می‌ماند.
   */
  axis_filter?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * برای ساخت ساختار درختی (اختیاری برای parent‌ها، الزامی برای leaf‌ها)
   */
  parent?: (number | null) | Category;
  /**
   * این فیلدها برای بهینه‌سازی موتورهای جستجو هستند. اگر خالی بگذارید، از عنوان و توضیح اصلی صفحه استفاده می‌شود.
   */
  seo?: {
    /**
     * عنوانی که در نتایج گوگل نشان داده می‌شود. بین ۵۰ تا ۶۰ کاراکتر توصیه می‌شود. اگر خالی باشد، عنوان اصلی صفحه استفاده می‌شود.
     */
    metaTitle?: string | null;
    /**
     * توضیح یک یا دو جمله‌ای زیر عنوان در نتایج گوگل. ۱۵۰ تا ۱۶۰ کاراکتر ایده‌آل است.
     */
    metaDescription?: string | null;
    /**
     * تصویری که در شبکه‌های اجتماعی و اپ‌های پیام‌رسان هنگام اشتراک‌گذاری لینک نمایش داده می‌شود. ابعاد پیشنهادی: ۱۲۰۰×۶۳۰. اگر خالی باشد، تصویر کاور خودکار ساخته می‌شود.
     */
    ogImage?: (number | null) | Media;
    /**
     * اگر این محتوا در جای دیگری نسخه اصلی دارد (مثلاً یک مجله‌ی دیگر) اینجا را پر کنید. معمولاً خالی بگذارید.
     */
    canonicalUrl?: string | null;
    /**
     * اگر روشن باشد، این صفحه در نتایج گوگل نمایش داده نمی‌شود. برای صفحات تست یا در حال ساخت مفید است.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  /**
   * Auto-generated from name if left empty
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "materials".
 */
export interface Material {
  id: number;
  name: string;
  /**
   * Auto-generated from name if left empty
   */
  slug?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (number | null) | Media;
  /**
   * مثال: «بلژیک»، «گرگان»
   */
  origin?: string | null;
  careNotes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  relatedArticles?: (number | Article)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * Auto-generated from title if left empty
   */
  slug?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * خلاصه‌ی کوتاه برای صفحات فهرست و کارت‌ها (حداکثر ۲۸۰ حرف)
   */
  excerpt: string;
  /**
   * اختیاری در حال حاضر — اگر خالی باشد، صفحه از تصویر پیش‌فرض استفاده می‌کند.
   */
  cover?: (number | null) | Media;
  author: number | Author;
  category: number | JournalCategory;
  tagIds?: (number | Tag)[] | null;
  relatedProducts?: (number | Product)[] | null;
  relatedArticles?: (number | Article)[] | null;
  /**
   * Auto-computed from body word count
   */
  readingTimeMinutes?: number | null;
  featured?: boolean | null;
  /**
   * فقط ویراستار یا مدیر می‌تواند وضعیت را به «منتشرشده» تغییر دهد.
   */
  status: 'draft' | 'published';
  publishedAt?: string | null;
  /**
   * این فیلدها برای بهینه‌سازی موتورهای جستجو هستند. اگر خالی بگذارید، از عنوان و توضیح اصلی صفحه استفاده می‌شود.
   */
  seo?: {
    /**
     * عنوانی که در نتایج گوگل نشان داده می‌شود. بین ۵۰ تا ۶۰ کاراکتر توصیه می‌شود. اگر خالی باشد، عنوان اصلی صفحه استفاده می‌شود.
     */
    metaTitle?: string | null;
    /**
     * توضیح یک یا دو جمله‌ای زیر عنوان در نتایج گوگل. ۱۵۰ تا ۱۶۰ کاراکتر ایده‌آل است.
     */
    metaDescription?: string | null;
    /**
     * تصویری که در شبکه‌های اجتماعی و اپ‌های پیام‌رسان هنگام اشتراک‌گذاری لینک نمایش داده می‌شود. ابعاد پیشنهادی: ۱۲۰۰×۶۳۰. اگر خالی باشد، تصویر کاور خودکار ساخته می‌شود.
     */
    ogImage?: (number | null) | Media;
    /**
     * اگر این محتوا در جای دیگری نسخه اصلی دارد (مثلاً یک مجله‌ی دیگر) اینجا را پر کنید. معمولاً خالی بگذارید.
     */
    canonicalUrl?: string | null;
    /**
     * اگر روشن باشد، این صفحه در نتایج گوگل نمایش داده نمی‌شود. برای صفحات تست یا در حال ساخت مفید است.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  /**
   * Auto-generated from name if left empty
   */
  slug?: string | null;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  avatar?: (number | null) | Media;
  role?: string | null;
  social?: {
    instagram?: string | null;
    telegram?: string | null;
    website?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-categories".
 */
export interface JournalCategory {
  id: number;
  name: string;
  /**
   * Auto-generated from name if left empty
   */
  slug?: string | null;
  description?: string | null;
  /**
   * این فیلدها برای بهینه‌سازی موتورهای جستجو هستند. اگر خالی بگذارید، از عنوان و توضیح اصلی صفحه استفاده می‌شود.
   */
  seo?: {
    /**
     * عنوانی که در نتایج گوگل نشان داده می‌شود. بین ۵۰ تا ۶۰ کاراکتر توصیه می‌شود. اگر خالی باشد، عنوان اصلی صفحه استفاده می‌شود.
     */
    metaTitle?: string | null;
    /**
     * توضیح یک یا دو جمله‌ای زیر عنوان در نتایج گوگل. ۱۵۰ تا ۱۶۰ کاراکتر ایده‌آل است.
     */
    metaDescription?: string | null;
    /**
     * تصویری که در شبکه‌های اجتماعی و اپ‌های پیام‌رسان هنگام اشتراک‌گذاری لینک نمایش داده می‌شود. ابعاد پیشنهادی: ۱۲۰۰×۶۳۰. اگر خالی باشد، تصویر کاور خودکار ساخته می‌شود.
     */
    ogImage?: (number | null) | Media;
    /**
     * اگر این محتوا در جای دیگری نسخه اصلی دارد (مثلاً یک مجله‌ی دیگر) اینجا را پر کنید. معمولاً خالی بگذارید.
     */
    canonicalUrl?: string | null;
    /**
     * اگر روشن باشد، این صفحه در نتایج گوگل نمایش داده نمی‌شود. برای صفحات تست یا در حال ساخت مفید است.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-variants".
 */
export interface ProductVariant {
  id: number;
  product: number | Product;
  /**
   * مثلاً GAN-BED-120-H. الزامی و یکتا.
   */
  sku: string;
  /**
   * متن نمایشی در سبد و فاکتورها. اگر خالی باشد، از نام محصول و محورهای واریانت خودکار ساخته می‌شود.
   */
  label?: string | null;
  /**
   * هر سطر یک محور (مثلاً سایز=۱۲۰). کلیدها باید با allowed_axes دسته‌بندی محصول هم‌خوان باشند.
   */
  axes?:
    | {
        /**
         * مثل size, footboard, doors, drawers, glass, width, pieces
         */
        key: string;
        /**
         * مثل 120, high, 3, true
         */
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * به قیمت پایه‌ی محصول اضافه می‌شود. می‌تواند صفر، مثبت، یا منفی باشد.
   */
  priceDeltaRials?: number | null;
  /**
   * در صورت تنظیم، جایگزین وضعیت محصول می‌شود. خالی = وضعیت محصول.
   */
  availability?: ('in_stock' | 'made_to_order' | 'backorder' | 'discontinued') | null;
  /**
   * اختیاری. در صورت تنظیم، با انتخاب این واریانت روی صفحه‌ی محصول cross-fade می‌شود.
   */
  image?: (number | null) | Media;
  /**
   * هرچه کمتر، اول. پیش‌فرض ۰. هنگام تساوی، مرتب‌سازی ثانویه بر اساس createdAt صعودی.
   */
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "showrooms".
 */
export interface Showroom {
  id: number;
  name: string;
  /**
   * Auto-generated from name if left empty
   */
  slug?: string | null;
  /**
   * یک جمله شاعرانه برای هیرو
   */
  headline?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  cover?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  address: {
    province?: string | null;
    city: string;
    district?: string | null;
    street?: string | null;
    plaque?: string | null;
    unit?: string | null;
    postalCode?: string | null;
    /**
     * مثال: نشانی نزدیک، پارکینگ
     */
    notes?: string | null;
  };
  geo?: {
    lat?: number | null;
    lng?: number | null;
  };
  /**
   * مثال: 081-38123456 یا +988138123456
   */
  phone: string;
  email?: string | null;
  hours?:
    | {
        day: 'sat' | 'sun' | 'mon' | 'tue' | 'wed' | 'thu' | 'fri';
        /**
         * الگو: HH:MM (مثال: 10:00)
         */
        opens?: string | null;
        /**
         * الگو: HH:MM (مثال: 20:00)
         */
        closes?: string | null;
        closed?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * مثال: نوروز ۱۴۰۵، شب یلدا
   */
  holidayHours?:
    | {
        name: string;
        date?: string | null;
        opens?: string | null;
        closes?: string | null;
        closed?: boolean | null;
        id?: string | null;
      }[]
    | null;
  appointmentOnly?: boolean | null;
  parkingNotes?: string | null;
  /**
   * مثال: نزدیکی به مترو / ایستگاه اتوبوس
   */
  transitNotes?: string | null;
  featuredProductIds?: (number | Product)[] | null;
  googleBusinessProfileUrl?: string | null;
  neshanProfileUrl?: string | null;
  /**
   * برای امبد نقشه. آدرس کامل iframe نشان یا OSM
   */
  mapEmbedUrl?: string | null;
  /**
   * Internal — not displayed on storefront
   */
  manager_name?: string | null;
  /**
   * Internal — SMS routing target for inquiries (Session 5.1)
   */
  manager_phone?: string | null;
  /**
   * Fallback for SMS routing when city has no match
   */
  is_central?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rooms".
 */
export interface Room {
  id: number;
  name: string;
  /**
   * ASCII فقط: kid, teen, adult
   */
  slug: string;
  /**
   * اپراتور باید تصویر کاور را پیش از انتشار آپلود کند. اتاق‌های بدون کاور در صفحه‌ی اصلی نمایش داده نمی‌شوند.
   */
  cover?: (number | null) | Media;
  /**
   * یک جمله که در کارت روی صفحه‌ی اصلی دیده می‌شود.
   */
  tagline?: string | null;
  longDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * این فیلدها برای بهینه‌سازی موتورهای جستجو هستند. اگر خالی بگذارید، از عنوان و توضیح اصلی صفحه استفاده می‌شود.
   */
  seo?: {
    /**
     * عنوانی که در نتایج گوگل نشان داده می‌شود. بین ۵۰ تا ۶۰ کاراکتر توصیه می‌شود. اگر خالی باشد، عنوان اصلی صفحه استفاده می‌شود.
     */
    metaTitle?: string | null;
    /**
     * توضیح یک یا دو جمله‌ای زیر عنوان در نتایج گوگل. ۱۵۰ تا ۱۶۰ کاراکتر ایده‌آل است.
     */
    metaDescription?: string | null;
    /**
     * تصویری که در شبکه‌های اجتماعی و اپ‌های پیام‌رسان هنگام اشتراک‌گذاری لینک نمایش داده می‌شود. ابعاد پیشنهادی: ۱۲۰۰×۶۳۰. اگر خالی باشد، تصویر کاور خودکار ساخته می‌شود.
     */
    ogImage?: (number | null) | Media;
    /**
     * اگر این محتوا در جای دیگری نسخه اصلی دارد (مثلاً یک مجله‌ی دیگر) اینجا را پر کنید. معمولاً خالی بگذارید.
     */
    canonicalUrl?: string | null;
    /**
     * اگر روشن باشد، این صفحه در نتایج گوگل نمایش داده نمی‌شود. برای صفحات تست یا در حال ساخت مفید است.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections".
 */
export interface Collection {
  id: number;
  name: string;
  /**
   * Auto-generated from name if left empty
   */
  slug?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  cover?: (number | null) | Media;
  products: (number | Product)[];
  featured?: boolean | null;
  /**
   * این فیلدها برای بهینه‌سازی موتورهای جستجو هستند. اگر خالی بگذارید، از عنوان و توضیح اصلی صفحه استفاده می‌شود.
   */
  seo?: {
    /**
     * عنوانی که در نتایج گوگل نشان داده می‌شود. بین ۵۰ تا ۶۰ کاراکتر توصیه می‌شود. اگر خالی باشد، عنوان اصلی صفحه استفاده می‌شود.
     */
    metaTitle?: string | null;
    /**
     * توضیح یک یا دو جمله‌ای زیر عنوان در نتایج گوگل. ۱۵۰ تا ۱۶۰ کاراکتر ایده‌آل است.
     */
    metaDescription?: string | null;
    /**
     * تصویری که در شبکه‌های اجتماعی و اپ‌های پیام‌رسان هنگام اشتراک‌گذاری لینک نمایش داده می‌شود. ابعاد پیشنهادی: ۱۲۰۰×۶۳۰. اگر خالی باشد، تصویر کاور خودکار ساخته می‌شود.
     */
    ogImage?: (number | null) | Media;
    /**
     * اگر این محتوا در جای دیگری نسخه اصلی دارد (مثلاً یک مجله‌ی دیگر) اینجا را پر کنید. معمولاً خالی بگذارید.
     */
    canonicalUrl?: string | null;
    /**
     * اگر روشن باشد، این صفحه در نتایج گوگل نمایش داده نمی‌شود. برای صفحات تست یا در حال ساخت مفید است.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: number;
  name: string;
  phone: string;
  city: string;
  reason: 'price_inquiry' | 'showroom_visit';
  preferred_date?: string | null;
  message?: string | null;
  /**
   * Auto-set by SMS routing logic (Session 5.1)
   */
  routed_to?: (number | null) | Showroom;
  /**
   * Set when submitted from a product detail page
   */
  product?: (number | null) | Product;
  /**
   * واریانت دقیقی که کاربر در PDP انتخاب کرده. در صورت محصول تک‌SKU خالی است.
   */
  productVariant?: (number | null) | ProductVariant;
  /**
   * snapshot کلید/مقدار از زمان ارسال. مثلاً {"size":"160","footboard":"high"}.
   */
  selectedAxes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status?: ('new' | 'contacted' | 'closed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  /**
   * فرمت ذخیره: 09xxxxxxxxx (نرمال‌سازی در /api/newsletter)
   */
  phone: string;
  subscribedAt: string;
  /**
   * مثلاً footer یا blog-popup
   */
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'designs';
        value: number | Design;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'product-variants';
        value: number | ProductVariant;
      } | null)
    | ({
        relationTo: 'showrooms';
        value: number | Showroom;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'journal-categories';
        value: number | JournalCategory;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'rooms';
        value: number | Room;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'materials';
        value: number | Material;
      } | null)
    | ({
        relationTo: 'collections';
        value: number | Collection;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: number | Inquiry;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "designs_select".
 */
export interface DesignsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  age_group?: T;
  occupancies?: T;
  description?: T;
  tagline?: T;
  heroMedia?: T;
  sliderMedia?: T;
  storyBlocks?: T;
  gallery?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  tagline?: T;
  shortDescription?: T;
  longDescription?: T;
  design?: T;
  piece_type?: T;
  occupancies?: T;
  categoryIds?: T;
  tagIds?: T;
  materialIds?: T;
  sku?: T;
  basePriceRials?: T;
  salePriceRials?: T;
  availability?: T;
  leadTimeDays?: T;
  warrantyYears?: T;
  afterSalesYears?: T;
  dimensions?:
    | T
    | {
        width?: T;
        height?: T;
        depth?: T;
      };
  gallery?: T;
  specs?: T;
  relatedProductIds?: T;
  pairsWithProductIds?: T;
  inquiry_enabled?: T;
  featured?: T;
  featuredOrder?: T;
  status?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-variants_select".
 */
export interface ProductVariantsSelect<T extends boolean = true> {
  product?: T;
  sku?: T;
  label?: T;
  axes?:
    | T
    | {
        key?: T;
        value?: T;
        id?: T;
      };
  priceDeltaRials?: T;
  availability?: T;
  image?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "showrooms_select".
 */
export interface ShowroomsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  headline?: T;
  description?: T;
  cover?: T;
  gallery?: T;
  address?:
    | T
    | {
        province?: T;
        city?: T;
        district?: T;
        street?: T;
        plaque?: T;
        unit?: T;
        postalCode?: T;
        notes?: T;
      };
  geo?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  phone?: T;
  email?: T;
  hours?:
    | T
    | {
        day?: T;
        opens?: T;
        closes?: T;
        closed?: T;
        id?: T;
      };
  holidayHours?:
    | T
    | {
        name?: T;
        date?: T;
        opens?: T;
        closes?: T;
        closed?: T;
        id?: T;
      };
  appointmentOnly?: T;
  parkingNotes?: T;
  transitNotes?: T;
  featuredProductIds?: T;
  googleBusinessProfileUrl?: T;
  neshanProfileUrl?: T;
  mapEmbedUrl?: T;
  manager_name?: T;
  manager_phone?: T;
  is_central?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  body?: T;
  excerpt?: T;
  cover?: T;
  author?: T;
  category?: T;
  tagIds?: T;
  relatedProducts?: T;
  relatedArticles?: T;
  readingTimeMinutes?: T;
  featured?: T;
  status?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  bio?: T;
  avatar?: T;
  role?: T;
  social?:
    | T
    | {
        instagram?: T;
        telegram?: T;
        website?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-categories_select".
 */
export interface JournalCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  tagline?: T;
  cover?: T;
  intro?: T;
  allowed_axes?: T;
  rule?: T;
  axis_filter?: T;
  parent?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rooms_select".
 */
export interface RoomsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  cover?: T;
  tagline?: T;
  longDescription?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "materials_select".
 */
export interface MaterialsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  image?: T;
  origin?: T;
  careNotes?: T;
  relatedArticles?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_select".
 */
export interface CollectionsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  cover?: T;
  products?: T;
  featured?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  decorative?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  city?: T;
  reason?: T;
  preferred_date?: T;
  message?: T;
  routed_to?: T;
  product?: T;
  productVariant?: T;
  selectedAxes?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  phone?: T;
  subscribedAt?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  /**
   * این فیلد در نسخه‌ی بعدی حذف می‌شود. به‌جای آن heroSlides را پر کنید.
   */
  hero_media?: (number | null) | Media;
  hero_heading?: string | null;
  hero_subheading?: string | null;
  heroSlides?:
    | {
        image: number | Media;
        alt: string;
        /**
         * مسیر داخلی یا URL کامل. اگر خالی باشد اسلاید کلیک‌پذیر نیست.
         */
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  brand_statement?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * اختیاری — اگر خالی باشد، بخش درباره فقط متن نمایش می‌دهد.
   */
  about_media?: (number | null) | Media;
  about_background?: (number | null) | Media;
  featured_designs?: (number | Design)[] | null;
  journal_teaser_heading?: string | null;
  inquiry_cta_heading?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  title?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "atelier".
 */
export interface Atelier {
  id: number;
  title?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number;
  title?: string | null;
  phone?: string | null;
  email?: string | null;
  address?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  title?: string | null;
  items?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "care".
 */
export interface Care {
  id: number;
  title?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title?: string | null;
  items?:
    | {
        title: string;
        description?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        date?: string | null;
        location?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy".
 */
export interface Privacy {
  id: number;
  title?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "returns".
 */
export interface Return {
  id: number;
  title?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping".
 */
export interface Shipping {
  id: number;
  title?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-config".
 */
export interface SiteConfig {
  id: number;
  /**
   * فرمت بین‌المللی نمایش داده می‌شود (مثلاً ۰۸۱-۳۴۲۵ ۶۷۸۹).
   */
  contactPhone?: string | null;
  contactEmail?: string | null;
  address?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * مثلاً: شنبه تا چهارشنبه، ۹ تا ۱۸
   */
  hours?: string | null;
  socials?:
    | {
        platform: 'instagram' | 'telegram' | 'whatsapp' | 'aparat' | 'youtube' | 'linkedin' | 'pinterest';
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms".
 */
export interface Term {
  id: number;
  title?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  hero_media?: T;
  hero_heading?: T;
  hero_subheading?: T;
  heroSlides?:
    | T
    | {
        image?: T;
        alt?: T;
        link?: T;
        id?: T;
      };
  brand_statement?: T;
  about_media?: T;
  about_background?: T;
  featured_designs?: T;
  journal_teaser_heading?: T;
  inquiry_cta_heading?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "atelier_select".
 */
export interface AtelierSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  title?: T;
  phone?: T;
  email?: T;
  address?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  title?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "care_select".
 */
export interface CareSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  items?:
    | T
    | {
        title?: T;
        description?: T;
        date?: T;
        location?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy_select".
 */
export interface PrivacySelect<T extends boolean = true> {
  title?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "returns_select".
 */
export interface ReturnsSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping_select".
 */
export interface ShippingSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-config_select".
 */
export interface SiteConfigSelect<T extends boolean = true> {
  contactPhone?: T;
  contactEmail?: T;
  address?: T;
  hours?: T;
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms_select".
 */
export interface TermsSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}